### ISSUE TITLE
Missing font in resources

### ISSUE THREAD

**Issue by parasj** [strap/strapkit#19]
```
Running command: /Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/strapkit/build 
/Users/parasjain/Dropbox/Code/testapp123123
From /Users/parasjain/Dropbox/Code/testapp123123/js
 * [new branch]      master     -> new
/Users/parasjain/Dropbox/Code/testapp123123
/Users/parasjain/Dropbox/Code/testapp123123
From /Users/parasjain/Dropbox/Code/testapp123123/resources/pebble
 * [new branch]      master     -> new
/Users/parasjain/Dropbox/Code/testapp123123
Setting top to                           : /Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123 
Setting out to                           : /Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123/build 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK in			 : /Users/parasjain/pebble-dev/PebbleSDK-2.8.1/Pebble
'configure' finished successfully (0.036s)
Waf: Entering directory `/Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123/build'
[ 2/28] UbuntuMono-Regular.ttf.MONO_FONT_14.pfo: resources/fonts/UbuntuMono-Regular.ttf ../../../../../../pebble-dev/PebbleSDK-2.8.1/Pebble/tools/font/fontgen.py -> build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo
Traceback (most recent call last):
  File "/Users/parasjain/pebble-dev/PebbleSDK-2.8.1/Pebble/tools/font/fontgen.py", line 4, in <module>
    import freetype
  File "/Users/parasjain/pebble-dev/PebbleSDK-current/.env/lib/python2.7/site-packages/freetype/__init__.py", line 38, in <module>
    raise RuntimeError, 'Freetype library not found'
RuntimeError: Freetype library not found
Waf: Leaving directory `/Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123/build'
Build failed
 -> task in 'UbuntuMono-Regular.ttf.MONO_FONT_14.pfo' failed (exit status 1): 
	{task 4553612240: UbuntuMono-Regular.ttf.MONO_FONT_14.pfo UbuntuMono-Regular.ttf,fontgen.py -> UbuntuMono-Regular.ttf.MONO_FONT_14.pfo}
" python '/Users/parasjain/pebble-dev/PebbleSDK-2.8.1/Pebble/tools/font/fontgen.py' pfo  14     '/Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123/resources/fonts/UbuntuMono-Regular.ttf' '/Users/parasjain/Dropbox/Code/testapp123123/platforms/pebble/testapp123123/build/resources/fonts/UbuntuMono-Regular.ttf.MONO_FONT_14.pfo' "
[ERROR   ] A compilation error occurred
```

**Comment by backjo** [comment]
Looks like you're missing the Freetype library. If you've got brew installed (if not, grab it @ http://brew.sh/), just run the following, and you should be good to go!
```
brew install freetype
```

**Comment by parasj** [comment]
Thanks! That fixed it.
